const {test}=require('node:test'),assert=require('node:assert/strict');require('../assets/zahlenfluss-store.js');require('../assets/warenfluss-store.js');require('../assets/restore-core.js');const R=globalThis.LadenflussRestore,Z=globalThis.Zahlenfluss,W=globalThis.Warenfluss;
const z={version:1,target:50000,entries:[Z.entry({date:'2026-10-08',revenue:'10,25'})]};const w={version:1,articles:[],movements:[]};
function storage(seed={}){const m=new Map(Object.entries(seed));return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),map:m};}
test('Restore: direct backup retains cents and only known data fields',()=>{const incoming={...z,secret:'not persisted'};assert.deepEqual(R.parse('zahlenfluss',JSON.stringify(incoming)),z);assert.equal(R.parse('zahlenfluss','\ufeff'+JSON.stringify(z)).entries[0].revenue,1025);});
test('Restore: full backup extracts only selected module, leaves auth and other modules alone',()=>{const s=storage({[W.KEY]:'inventory','ladenfluss.auth.v1':'private'});const full={format:'ladenfluss-local-backup',version:1,records:{[Z.KEY]:JSON.stringify(z),'ladenfluss.auth.v1':'malicious'}};const p=R.prepare('zahlenfluss',JSON.stringify(full),s);assert.equal(s.getItem(Z.KEY),null);R.apply(p,s);assert.deepEqual(JSON.parse(s.getItem(Z.KEY)),z);assert.equal(s.getItem(W.KEY),'inventory');assert.equal(s.getItem('ladenfluss.auth.v1'),'private');});
test('Restore: wrong module, malformed JSON, unsupported version and oversized files rejected',()=>{for(const text of ['{',JSON.stringify(w),JSON.stringify({...z,version:99}),JSON.stringify({format:'ladenfluss-local-backup',version:1,records:{}})])assert.throws(()=>R.parse('zahlenfluss',text));assert.throws(()=>R.parse('zahlenfluss',' '.repeat(R.MAX_BYTES+1)));});
test('Restore: stale preview and quota failure preserve existing data',()=>{const s=storage({[Z.KEY]:'old'}),p=R.prepare('zahlenfluss',JSON.stringify(z),s);s.setItem(Z.KEY,'changed');assert.throws(()=>R.apply(p,s),/geändert/);assert.equal(s.getItem(Z.KEY),'changed');const q=R.prepare('zahlenfluss',JSON.stringify(z),s);s.setItem=()=>{throw Error('QuotaExceededError');};assert.throws(()=>R.apply(q,s),/Speichern fehlgeschlagen/);assert.equal(s.getItem(Z.KEY),'changed');});
test('Restore: broken existing data may be replaced only after valid preview',()=>{const s=storage({[W.KEY]:'{broken'}),p=R.prepare('warenfluss',JSON.stringify(w),s);assert.match(p.current,/nicht lesbar/);assert.equal(s.getItem(W.KEY),'{broken');R.apply(p,s);assert.deepEqual(JSON.parse(s.getItem(W.KEY)),w);});
test('Restore: invalid inventory references and negative balances rejected',()=>{const d={version:1,articles:[{id:'a',name:'Coffee',sku:'A',minimum:0,archived:false}],movements:[{id:'m',articleId:'a',type:'issue',delta:-1,note:'Sale',at:'2026-10-08T12:00:00Z'}]};assert.throws(()=>R.parse('warenfluss',JSON.stringify(d)));d.movements[0].delta=1;d.movements[0].type='receipt';d.movements[0].articleId='missing';assert.throws(()=>R.parse('warenfluss',JSON.stringify(d)));});

test('Restore: monthly targets survive backup roundtrip without changing weekly target',()=>{const data={...z,monthlyTargets:{'2026-09':1250000,'2026-10':1500000}};const s=storage();const p=R.prepare('zahlenfluss',JSON.stringify(data),s);R.apply(p,s);assert.deepEqual(JSON.parse(s.getItem(Z.KEY)),data);assert.match(p.incoming,/2 Monatsziele/);});
