const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {JSDOM}=require('jsdom');
function setup(){const dom=new JSDOM('',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;w.TextEncoder=TextEncoder;for(const name of ['signals','planning-engine','de-holidays','team-storage','team-store','urlaubsplaner-store','team-restore','backup'])w.eval(fs.readFileSync(path.join(__dirname,'../assets/'+name+'.js'),'utf8'));return dom;}
function fixture(){return {format:'ladenfluss-local-backup',version:1,records:{'ladenfluss.team.v1':JSON.stringify([{id:'a',name:'Alex',role:'Verkauf',branch:'Hauptfiliale',hours:30,docs:true}]),'ladenfluss.pep.weeks.v2':JSON.stringify({'2026-10-05':{a:[null,['09:00','17:00',30],null,null,null,null,null]}}),'ladenfluss.urlaubsplaner.v1':JSON.stringify({version:1,employees:[{id:'a',name:'Alex',allowance:30}],entries:[{id:'v',employeeId:'a',start:'2026-10-06',end:'2026-10-06',status:'approved',note:''}],settings:{state:'HE',workdays:[1,2,3,4,5],maxAbsent:1}})}};}
test('Team restore: atomic package is read and edited by existing stores and exports',()=>{const d=setup(),w=d.window,s=w.localStorage,R=w.LadenflussTeamRestore;const p=R.prepare(JSON.stringify(fixture()),s);R.apply(p,s);assert.equal(w.LadenflussTeamStore.getTeam()[0].name,'Alex');assert.equal(w.LadenflussVacation.read().entries.length,1);const team=w.LadenflussTeamStore.getTeam();team[0].hours=32;w.LadenflussTeamStore.saveTeam(team);assert.equal(w.LadenflussTeamStore.getTeam()[0].hours,32);assert.equal(JSON.parse(w.LadenflussBackup.capture().records['ladenfluss.team.v1'])[0].hours,32);assert.equal(w.LadenflussTeamStore.getShifts('2026-10-05').a[1][0],'09:00');d.window.close();});
test('Team restore: dangling shift IDs and conflicting identities reject the entire package',()=>{const d=setup(),R=d.window.LadenflussTeamRestore;let f=fixture();f.records['ladenfluss.team.v1']='[]';assert.throws(()=>R.parse(JSON.stringify(f)),/unbekannte Mitarbeiter-ID/);f=fixture();const v=JSON.parse(f.records['ladenfluss.urlaubsplaner.v1']);v.employees[0].name='Someone else';f.records['ladenfluss.urlaubsplaner.v1']=JSON.stringify(v);assert.throws(()=>R.parse(JSON.stringify(f)),/unterschiedliche Namen/);d.window.close();});
test('Team restore: failed single write leaves every original key unchanged',()=>{const d=setup(),R=d.window.LadenflussTeamRestore,values=new Map([['ladenfluss.team.v1','[]'],['ladenfluss.auth.v1','secret'],['ladenfluss.store.v1','profile']]);let writes=0;const storage={getItem:k=>values.get(k)??null,setItem:()=>{writes++;throw Error('quota');}};const before=JSON.stringify([...values]),p=R.prepare(JSON.stringify(fixture()),storage);assert.throws(()=>R.apply(p,storage),/bisherige Stand/);assert.equal(writes,1);assert.equal(JSON.stringify([...values]),before);d.window.close();});
test('Team restore: stale native or bundle edits invalidate preview',()=>{const d=setup(),w=d.window,R=w.LadenflussTeamRestore,s=w.localStorage;let p=R.prepare(JSON.stringify(fixture()),s);s.setItem('ladenfluss.pep.absences.v1','{}');assert.throws(()=>R.apply(p,s),/geändert/);p=R.prepare(JSON.stringify(fixture()),s);R.apply(p,s);p=R.prepare(JSON.stringify(fixture()),s);w.LadenflussTeamStore.saveTeam([]);assert.throws(()=>R.apply(p,s),/geändert/);d.window.close();});
test('Team restore: independent vacation IDs stay separate and missing plans are explicit empty records',()=>{const d=setup(),R=d.window.LadenflussTeamRestore,f=fixture();delete f.records['ladenfluss.pep.weeks.v2'];const v=JSON.parse(f.records['ladenfluss.urlaubsplaner.v1']);v.employees[0].id='independent';v.entries[0].employeeId='independent';f.records['ladenfluss.urlaubsplaner.v1']=JSON.stringify(v);const p=R.parse(JSON.stringify(f));assert.match(p.summary,/1 Urlaubspersonen ohne Team-Zuordnung/);assert.equal(p.records['ladenfluss.pep.weeks.v2'],'{}');assert.equal(p.records['ladenfluss.pep.shifts.v1'],null);d.window.close();});
test('Team restore: legacy dates and malformed bundles fail without default seeding',()=>{const d=setup(),w=d.window,f=fixture();delete f.records['ladenfluss.pep.weeks.v2'];f.records['ladenfluss.pep.shifts.v1']=JSON.stringify({a:[null,null,null,null,null,null,null]});assert.throws(()=>w.LadenflussTeamRestore.parse(JSON.stringify(f)),/Wochendatum/);w.localStorage.setItem(w.LadenflussTeamStorage.KEY,'{bad');assert.throws(()=>w.LadenflussTeamStore.getTeam());assert.equal(w.localStorage.getItem(w.LadenflussTeamStorage.KEY),'{bad');d.window.close();});
