const {test}=require('node:test');const assert=require('node:assert/strict');const W=require('../assets/warenfluss-store.js');
function fixture(){const d={version:1,articles:[],movements:[]};W.article(d,{name:'Kaffee',sku:'K01',minimum:'5'},'a');return d;}
const move=(d,type,quantity,extra={})=>W.move(d,{articleId:'a',type,quantity,note:'Beleg',...extra},String(d.movements.length),'2026-10-08T12:00:00Z');
test('Warenfluss: receipt, issue and correction keep an auditable balance',()=>{const d=fixture();move(d,'receipt','10');move(d,'issue','3');move(d,'correction','2',{direction:'minus'});assert.equal(W.stock(d,'a'),5);assert.equal(d.movements.length,3);assert.equal(W.validate(d),d);});
test('Warenfluss: rejects negative stock, blank reason, fractional quantities and duplicate SKU',()=>{const d=fixture();for(const q of ['1','-1','1.5','1e3'])assert.throws(()=>move(d,'issue',q));assert.throws(()=>move(d,'receipt','1',{note:''}));assert.throws(()=>W.article(d,{name:'Tea',sku:'k01',minimum:0},'b'));assert.equal(d.movements.length,0);});
test('Warenfluss: archive preserves history and cannot hide remaining inventory',()=>{const d=fixture();move(d,'receipt','2');assert.throws(()=>W.archive(d,'a'));move(d,'issue','2');W.archive(d,'a');assert.throws(()=>move(d,'receipt','1'));assert.equal(d.movements.length,2);W.archive(d,'a');move(d,'receipt','1');assert.equal(W.stock(d,'a'),1);});
test('Warenfluss: damaged history is rejected without reset',()=>{const d=fixture();move(d,'receipt','2');d.movements[0].articleId='unknown';assert.throws(()=>W.load({getItem:()=>JSON.stringify(d)}));assert.throws(()=>W.load({getItem:()=>'{'}));});
test('Warenfluss: CSV escapes formulas and quotes',()=>{const d=fixture();d.articles[0].name='=HYPERLINK("bad")';assert.match(W.csv(d),/'=HYPERLINK\(""bad""\)/);});

test('Warenfluss: one delivery books all positions with linked immutable receipt snapshots',()=>{const d=fixture();W.article(d,{name:'Tea',sku:'T01',minimum:0},'b');W.supplier(d,{name:'Großhandel',contact:'Alex'},'s');W.receive(d,{supplierId:'s',reference:'LS-1',date:'2026-10-09',lines:[{articleId:'a',quantity:10},{articleId:'b',quantity:4}]},'delivery-1','2026-10-09T12:00:00Z');assert.equal(W.stock(d,'a'),10);assert.equal(W.stock(d,'b'),4);assert.equal(d.movements.length,2);assert.equal(d.deliveries[0].lines.length,2);W.supplier(d,{name:'Neuer Name',contact:''},'s');assert.equal(d.deliveries[0].supplierName,'Großhandel');assert.equal(W.validate(d),d);});
test('Warenfluss: failure in a later delivery line makes no partial booking',()=>{const d=fixture();W.supplier(d,{name:'Supplier',contact:''},'s');const before=JSON.stringify(d);assert.throws(()=>W.receive(d,{supplierId:'s',reference:'LS-1',date:'2026-10-09',lines:[{articleId:'a',quantity:10},{articleId:'missing',quantity:1}]},'d','2026-10-09T12:00:00Z'));assert.equal(JSON.stringify(d),before);});
test('Warenfluss: duplicate document, repeated article and archived supplier are rejected',()=>{const d=fixture();W.supplier(d,{name:'Supplier',contact:''},'s');const raw={supplierId:'s',reference:'LS-1',date:'2026-10-09',lines:[{articleId:'a',quantity:1}]};assert.throws(()=>W.receive(d,{...raw,lines:[...raw.lines,...raw.lines]},'x','2026-10-09T12:00:00Z'));W.receive(d,raw,'d','2026-10-09T12:00:00Z');assert.throws(()=>W.receive(d,{...raw,reference:'ls-1'},'e','2026-10-09T12:00:00Z'),/bereits gebucht/);d.suppliers[0].archived=true;assert.throws(()=>W.receive(d,{...raw,reference:'LS-2'},'f','2026-10-09T12:00:00Z'));assert.equal(W.stock(d,'a'),1);});
test('Warenfluss: broken delivery references fail validation',()=>{const d=fixture();W.supplier(d,{name:'Supplier',contact:''},'s');W.receive(d,{supplierId:'s',reference:'LS-1',date:'2026-10-09',lines:[{articleId:'a',quantity:1}]},'d','2026-10-09T12:00:00Z');d.deliveries[0].lines[0].quantity=2;assert.throws(()=>W.validate(d),/passen nicht/);});
