name: ladenfluss_wws
description: Ladenfluss WWS Desktop – macOS und Windows
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.35.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
